---
- name: Check VM Disks
  hosts: all
  gather_facts: yes
  tasks:
    - name: Collect Hardware Facts
      setup:
        gather_subset:
          - 'hardware'

    - name: Test for available disk space
      setup: filter=ansible_mounts
      
    - name: Ensure that free space on the tested volume is greater than 25%
      assert:
        that:
          - mount.size_available > mount.size_total|float * 0.25
        msg: Disk space has reached 75% threshold
      vars:
        mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
      with_items:
        - "{{ ansible_mounts }}"