---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      ansible.builtin.shell: sudo apt update && sudo apt upgrade -y

    - name: email result
      mail:
        to: mike@upshon.net
        subject: "updates applied to {{ ansible_hostname }}"
        body: "{{ item }}"
      with_items: "{{ updated.results|map(attribute='stdout_lines')|list }}"
      when: updated.stdout      