---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      shell: sudo apt update && sudo apt upgrade -y
      register: command_log

    - name: email result
      mail:
        subject: "update apt packages"
        body: "{{ command_log.stdout }}"
      when: command_log.stdout      
      delegate_to: localhost